
spring:
  application:
    name: peer2
  profiles: peer2
server:
  port: 8762

eureka:
  instance:
    hostname: peer2
    #prefer-ip-address: true
    #appname: eureka-server
  client:
    #通过eureka.client.registerWithEureka：false和 fetchRegistry：false来表明自己是一个eureka server.
    register-with-eureka: false
    fetch-registry: false
    service-url:
        defaultZone: http://peer1:8761/eureka/


#显示服务器详细的健康信息
management:
  security:
    enabled: false


