eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 8769
spring:
  application:
    name: zuul-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon-service
    api-b:
      path: /api-b/**
      serviceId: feign-service
    api-c:
      path: /user-api/**
      serviceId: user-service